Add License file check for message queue module to determine whether …
paliarush/vagrant-magento pull request #182
Opened 2018-04-06 22:11 UTC by eric-bohanon

…or not to add --amqp-* options for install

2018-04-06 22:11 UTC, eric-bohanon commented
@paliarush review when you can

2018-04-10 15:46 UTC, paliarush requested changes

2018-04-10 15:46 UTC, paliarush commented on scripts/guest/m-reinstall
> +if [[ -f "${MAGENTO_ROOT}/app/code/Magento/MessageQueue/LICENSE.txt" ]]; then
This will fail for composer-based installation because all Magento modules are located in vendor in that case.

2018-04-10 16:55 UTC, eric-bohanon commented
Updated with the vendor directory and composer versioning instructions

2018-04-11 20:37 UTC, merged